### PR TITLE
Remove works previously published under CC BY-SA 3.0

### PR DESCRIPTION
**Pull request by davidlohle**
The new blog, which uses my own content under a different author, is licensed under the Apache License. The blog was originally under CC BY-SA 3.0, which allowed for the distribution of my modified work so long that it remained under the same license. I would like for my content to be removed, or for the blog to continue using the CC BY-SA 3.0 license. There is also another method to fix this violation.

Tox can continue to use my work verbatim under the Apache License; however, in order for the work to be verbatim, the author of the posts has to be changed from Tox Foundation to David Lohle. You can then use this PR as a list of articles and pages that need to be updated.

### CODE REVIEW

**Comment by urras** [comment]
Will 8e5807d work for you?

**Comment by davidlohle** [comment]
There's only one article that was actually updated, and it's just "David". Verbatim would be "David Lohle".

**Comment by urras** [comment]
@Proplex Oh, sorry. I'll go through and change the rest later this evening.

**Comment by irungentoo** [comment]
Everything on the blog was written for or on behalf of the tox foundation meaning it belongs to the tox foundation and not the individuals writing the blog posts.

Go troll somewhere else.

**Comment by urras** [comment]
Well that was a bit rude. I was actually in the middle of properly attributing all of Proplex's articles on the blog.

**Pull request merged**
