### PR TITLE
Cut the preview of the post

### PR DESCRIPTION
**Pull request by nurupo**
The post is too long, we need to cut it for the main page.
See https://blog.tox.im/ .

### CODE REVIEW

**Comment by dubslow** [comment]
Shouldn't it be cut at line 8?

**Comment by nurupo** [comment]
Why should it be cut at line 8?

**Comment by nurupo** [comment]
I think that a few sentences and `<read more>` is better than just a single sentence and `<read more>`. It helps the reader realize if it's something that s/he would be interested in reading more. Also, having posts that cut just after the first sentence is a bit annoying -- takes too much space on the main page without telling much.

Btw, not cutting the post is also an option. For example, github doesn't cut its blog. We do cut it for some time now, though.

**Comment by urras** [comment]
Any update @nurupo?

**Comment by dubslow** [comment]
Almost all the other previews are only a sentence or two, and that's about the size of the lead two sentences before breaking down into specific sections. I don't think any of the specific sections should be part of the preview, because that may give the false impression of being the only section discussed.

**Comment by nurupo** [comment]
Oh, this issue is still not closed. I already forgot about it : )

**Comment by nurupo** [comment]
Here, should be better.

**Comment by dubslow** [comment]
I'm good with this, urras?

**Comment by urras** [comment]
:+1:

**Pull request merged**
